# Generated by Django 4.0.4 on 2022-05-26 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255)),
                ('function_args', models.JSONField(blank=True, null=True)),
                ('interval', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('stream_name', models.SlugField(default='default')),
                ('group_name', models.SlugField(default='default')),
                ('last_message_id', models.CharField(editable=False, max_length=255, null=True)),
                ('ready_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 26, 21, 12, 21, 822735, tzinfo=utc))),
            ],
        ),
    ]
