# Generated by Django 4.0.5 on 2022-06-21 20:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedisDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Redis diagnostics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('.', 'Reload page to view options')], max_length=255)),
                ('task_args', models.JSONField(blank=True, default=dict)),
                ('interval', models.DurationField(default=datetime.timedelta(seconds=900), help_text='HH:MM:SS')),
                ('jitter', models.BooleanField(default=True, help_text='Apply a 5% jitter to the interval (e.g. 10s -> [9.5s, 10.5s])', verbose_name='Apply jitter?')),
                ('stream_name', models.SlugField(choices=[('drcg', 'Reload page to view options')], default='drcg')),
                ('last_message_id', models.CharField(editable=False, max_length=255, null=True)),
                ('ready_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
