# Generated by Django 4.0.5 on 2022-06-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='group_name',
            field=models.SlugField(choices=[('drcg', 'Reload page to view options')], default='drcg'),
        ),
    ]
