# Generated by Django 4.0.4 on 2022-05-26 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervaltask',
            name='ready_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
