# Generated by Django 4.0.4 on 2022-05-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0002_alter_intervaltask_ready_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervaltask',
            name='last_message_id',
            field=models.BinaryField(max_length=255, null=True),
        ),
    ]
