# Generated by Django 4.0.5 on 2022-06-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0002_scheduler_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='stream_name',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='consumergroup',
            field=models.SlugField(choices=[('drcg:drcg', 'Reload page to view options')], default='drcg:drcg'),
        ),
    ]
