# Generated by Django 4.0.5 on 2022-06-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0003_remove_scheduler_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='consumergroup',
            field=models.CharField(choices=[('drcg:drcg', 'Reload page to view options')], default='drcg:drcg', max_length=255),
        ),
    ]
