# Generated by Django 4.0.4 on 2022-05-26 22:26

import datetime
from django.db import migrations, models
import drcg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0003_alter_intervaltask_last_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervaltask',
            name='function_name',
            field=models.CharField(max_length=255, validators=[drcg.validators.validate_task_name]),
        ),
        migrations.AlterField(
            model_name='intervaltask',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='intervaltask',
            name='last_message_id',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
