# Generated by Django 4.0.4 on 2022-05-27 23:11

import datetime
from django.db import migrations, models
import django.utils.timezone
import drcg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0005_alter_intervaltask_function_args'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedisConsumerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedisStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255, validators=[drcg.validators.validate_task_name])),
                ('function_args', models.JSONField(blank=True, default=dict)),
                ('interval', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='HH:MM:SS')),
                ('stream_name', models.SlugField(default='drcg')),
                ('group_name', models.SlugField(default='drcg')),
                ('last_message_id', models.CharField(editable=False, max_length=255, null=True)),
                ('ready_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='IntervalTask',
        ),
    ]
