# Generated by Django 4.0.4 on 2022-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcg', '0006_redisconsumer_redisconsumergroup_redisstream_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='function_args',
            new_name='task_args',
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='function_name',
            new_name='task_name',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='jitter',
            field=models.BooleanField(default=True, help_text='Apply a 5% jitter to the interval (e.g. 10s -> [9.5s, 10.5s])', verbose_name='Apply jitter?'),
        ),
    ]
